extends: [a, plugin:tailwindcss/recommended]
ignorePatterns:
  - /out/
  - /next.config.js
  - /next-env.d.ts
plugins: [tailwindcss]
root: true
rules:
  # "@typescript-eslint/no-unsafe-return": off
  "@typescript-eslint/strict-boolean-expressions": off
  tailwindcss/classnames-order: error
